export const CIDADES_BRASIL: string[] = [
  // SP
  'São Paulo, SP',
  // SC
  'Aurora, SC',
  'Balneário Camboriú, SC',
  'Biguaçu, SC',
  'Blumenau, SC',
  'Braço do Norte, SC',
  'Chapecó, SC',
  'Cocal do Sul, SC',
  'Criciúma, SC',
  'Florianópolis, SC',
  'Gaspar, SC',
  'Guaramirim, SC',
  'Içara, SC',
  'Indaial, SC',
  'Itajaí, SC',
  'Jaraguá do Sul, SC',
  'Joaçaba, SC',
  'Joinville, SC',
  'Massaranduba, SC',
  'Morro da Fumaça, SC',
  'Orleans, SC',
  'Palhoça, SC',
  'Paulo Lopes, SC',
  'Pomerode, SC',
  'Santa Helena, SC',
  'São Bento do Sul, SC',
  'Timbó, SC',
  'Urussanga, SC',
  'Videira, SC',
  // RS
  'Bento Gonçalves, RS',
  'Bom Retiro do Sul, RS',
  'Campo Bom, RS',
  'Canoas, RS',
  'Caxias do Sul, RS',
  'Esteio, RS',
  'Farroupilha, RS',
  'Flores da Cunha, RS',
  'Garibaldi, RS',
  'Gravataí, RS',
  'Guaíba, RS',
  'Ivoti, RS',
  'Lajeado, RS',
  'Novo Hamburgo, RS',
  'Passo Fundo, RS',
  'Porto Alegre, RS',
  'Santa Maria, RS',
  'São José do Sul, RS',
  'São Leopoldo, RS',
  'São Sebastião do Caí, RS',
  'Sapiranga, RS',
  'Três Coroas, RS',
  'Tupandi, RS',
  'Vacaria, RS',
  // PR
  'Araucária, PR',
  'Cambé, PR',
  'Campina Grande do Sul, PR',
  'Campo Largo, PR',
  'Cascavel, PR',
  'Curitiba, PR',
  'Fazenda Rio Grande, PR',
  'Loanda, PR',
  'Londrina, PR',
  'Paranavaí, PR',
  'Rolândia, PR',
  'Toledo, PR',
  'União da Vitória, PR',
  // Outros
  'Rio de Janeiro, RJ',
  'Belo Horizonte, MG',
  'Campo Grande, MS',
  'Goiânia, GO',
  'Brasília, DF',
]
